/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.83
 * Generated at: 2022-11-21 05:22:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.tiles;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class aside_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/spring-security-taglibs-5.0.7.RELEASE.jar", Long.valueOf(1667797009443L));
    _jspx_dependants.put("jar:file:/C:/eGovFrameDev-3.10.0-64bit/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/egovProj/WEB-INF/lib/spring-security-taglibs-5.0.7.RELEASE.jar!/META-INF/security.tld", Long.valueOf(1532606274000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1666247059863L));
    _jspx_dependants.put("jar:file:/C:/eGovFrameDev-3.10.0-64bit/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/egovProj/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsec_005fcsrfInput_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsec_005fcsrfInput_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.release();
    _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody.release();
    _005fjspx_005ftagPool_005fsec_005fcsrfInput_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Main Sidebar Container -->\r\n");
      out.write("<aside class=\"main-sidebar sidebar-dark-primary elevation-4\">\r\n");
      out.write("  <!-- Brand Logo -->\r\n");
      out.write("  <a href=\"index3.html\" class=\"brand-link\">\r\n");
      out.write("    <img src=\"/resources/adminlte/dist/img/AdminLTELogo.png\" alt=\"AdminLTE Logo\" class=\"brand-image img-circle elevation-3\" style=\"opacity: .8\">\r\n");
      out.write("    <span class=\"brand-text font-weight-light\">개똥이페이</span>\r\n");
      out.write("  </a>\r\n");
      out.write("\r\n");
      out.write("  <!-- Sidebar -->\r\n");
      out.write("  <div class=\"sidebar\">\r\n");
      out.write("    <!-- Sidebar user panel (optional) -->\r\n");
      out.write("    <!-- 로그인을 하지 않은 경우 -->\r\n");
      out.write("    ");
      if (_jspx_meth_sec_005fauthorize_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("      	<!-- 인증된 사용자인 경우 -->\r\n");
      out.write("		");
      if (_jspx_meth_sec_005fauthorize_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    <!-- SidebarSearch Form -->\r\n");
      out.write("    <div class=\"form-inline\">\r\n");
      out.write("      <div class=\"input-group\" data-widget=\"sidebar-search\">\r\n");
      out.write("        <input class=\"form-control form-control-sidebar\" type=\"search\" placeholder=\"Search\" aria-label=\"Search\">\r\n");
      out.write("        <div class=\"input-group-append\">\r\n");
      out.write("          <button class=\"btn btn-sidebar\">\r\n");
      out.write("            <i class=\"fas fa-search fa-fw\"></i>\r\n");
      out.write("          </button>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Sidebar Menu -->\r\n");
      out.write("    <nav class=\"mt-2\">\r\n");
      out.write("      <ul class=\"nav nav-pills nav-sidebar flex-column\" data-widget=\"treeview\" role=\"menu\" data-accordion=\"false\">\r\n");
      out.write("        <!-- Add icons to the links using the .nav-icon class\r\n");
      out.write("             with font-awesome or any other icon font library -->\r\n");
      out.write("        <li class=\"nav-item menu-open\">\r\n");
      out.write("          <a href=\"#\" class=\"nav-link active\">\r\n");
      out.write("            <i class=\"nav-icon fas fa-tachometer-alt\"></i>\r\n");
      out.write("            <p>\r\n");
      out.write("              Dashboard\r\n");
      out.write("              <i class=\"right fas fa-angle-left\"></i>\r\n");
      out.write("            </p>\r\n");
      out.write("          </a>\r\n");
      out.write("          <ul class=\"nav nav-treeview\">\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a href=\"./index.html\" class=\"nav-link active\">\r\n");
      out.write("                <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                <p>Dashboard v1</p>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a href=\"./index2.html\" class=\"nav-link\">\r\n");
      out.write("                <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                <p>Dashboard v2</p>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a href=\"./index3.html\" class=\"nav-link\">\r\n");
      out.write("                <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                <p>Dashboard v3</p>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("        <!-- 도서관리 메뉴 시작 -->\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a href=\"#\" class=\"nav-link\">\r\n");
      out.write("            <i class=\"nav-icon fas fa-chart-pie\"></i>\r\n");
      out.write("            <p>도서관리\r\n");
      out.write("              <i class=\"right fas fa-angle-left\"></i>\r\n");
      out.write("            </p>\r\n");
      out.write("          </a>\r\n");
      out.write("          <ul class=\"nav nav-treeview\">\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a href=\"/book/list\" class=\"nav-link\">\r\n");
      out.write("                <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                <p>도서목록</p>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a href=\"/book/regist\" class=\"nav-link\">\r\n");
      out.write("                <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                <p>도서등록</p>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("        <!-- 도서관리 메뉴 끝 -->\r\n");
      out.write("           <!-- 도서관리 메뉴 시작 -->\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a href=\"#\" class=\"nav-link\">\r\n");
      out.write("            <i class=\"nav-icon fas fa-chart-pie\"></i>\r\n");
      out.write("            <p>이미지갤러리\r\n");
      out.write("              <i class=\"right fas fa-angle-left\"></i>\r\n");
      out.write("            </p>\r\n");
      out.write("          </a>\r\n");
      out.write("          <ul class=\"nav nav-treeview\">\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a href=\"/gallery/list\" class=\"nav-link\">\r\n");
      out.write("                <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                <p>이미지목록</p>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a href=\"/gallery/regist\" class=\"nav-link\">\r\n");
      out.write("                <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                <p>이미지등록</p>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("        <!-- 도서관리 메뉴 끝 -->\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a href=\"pages/widgets.html\" class=\"nav-link\">\r\n");
      out.write("            <i class=\"nav-icon fas fa-th\"></i>\r\n");
      out.write("            <p>\r\n");
      out.write("              Widgets\r\n");
      out.write("              <span class=\"right badge badge-danger\">New</span>\r\n");
      out.write("            </p>\r\n");
      out.write("          </a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a href=\"#\" class=\"nav-link\">\r\n");
      out.write("            <i class=\"nav-icon fas fa-copy\"></i>\r\n");
      out.write("            <p>\r\n");
      out.write("              Layout Options\r\n");
      out.write("              <i class=\"fas fa-angle-left right\"></i>\r\n");
      out.write("              <span class=\"badge badge-info right\">6</span>\r\n");
      out.write("            </p>\r\n");
      out.write("          </a>\r\n");
      out.write("          <ul class=\"nav nav-treeview\">\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a href=\"pages/layout/top-nav.html\" class=\"nav-link\">\r\n");
      out.write("                <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                <p>Top Navigation</p>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a href=\"pages/layout/top-nav-sidebar.html\" class=\"nav-link\">\r\n");
      out.write("                <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                <p>Top Navigation + Sidebar</p>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a href=\"pages/layout/boxed.html\" class=\"nav-link\">\r\n");
      out.write("                <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                <p>Boxed</p>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a href=\"pages/layout/fixed-sidebar.html\" class=\"nav-link\">\r\n");
      out.write("                <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                <p>Fixed Sidebar</p>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a href=\"pages/layout/fixed-sidebar-custom.html\" class=\"nav-link\">\r\n");
      out.write("                <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                <p>Fixed Sidebar <small>+ Custom Area</small></p>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a href=\"pages/layout/fixed-topnav.html\" class=\"nav-link\">\r\n");
      out.write("                <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                <p>Fixed Navbar</p>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a href=\"pages/layout/fixed-footer.html\" class=\"nav-link\">\r\n");
      out.write("                <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                <p>Fixed Footer</p>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a href=\"pages/layout/collapsed-sidebar.html\" class=\"nav-link\">\r\n");
      out.write("                <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                <p>Collapsed Sidebar</p>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a href=\"#\" class=\"nav-link\">\r\n");
      out.write("            <i class=\"nav-icon fas fa-chart-pie\"></i>\r\n");
      out.write("            <p>\r\n");
      out.write("              Charts\r\n");
      out.write("              <i class=\"right fas fa-angle-left\"></i>\r\n");
      out.write("            </p>\r\n");
      out.write("          </a>\r\n");
      out.write("          <ul class=\"nav nav-treeview\">\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a href=\"pages/charts/chartjs.html\" class=\"nav-link\">\r\n");
      out.write("                <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                <p>ChartJS</p>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a href=\"pages/charts/flot.html\" class=\"nav-link\">\r\n");
      out.write("                <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                <p>Flot</p>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a href=\"pages/charts/inline.html\" class=\"nav-link\">\r\n");
      out.write("                <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                <p>Inline</p>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a href=\"pages/charts/uplot.html\" class=\"nav-link\">\r\n");
      out.write("                <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                <p>uPlot</p>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a href=\"#\" class=\"nav-link\">\r\n");
      out.write("            <i class=\"nav-icon fas fa-tree\"></i>\r\n");
      out.write("            <p>\r\n");
      out.write("              UI Elements\r\n");
      out.write("              <i class=\"fas fa-angle-left right\"></i>\r\n");
      out.write("            </p>\r\n");
      out.write("          </a>\r\n");
      out.write("          <ul class=\"nav nav-treeview\">\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a href=\"pages/UI/general.html\" class=\"nav-link\">\r\n");
      out.write("                <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                <p>General</p>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a href=\"pages/UI/icons.html\" class=\"nav-link\">\r\n");
      out.write("                <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                <p>Icons</p>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a href=\"pages/UI/buttons.html\" class=\"nav-link\">\r\n");
      out.write("                <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                <p>Buttons</p>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a href=\"pages/UI/sliders.html\" class=\"nav-link\">\r\n");
      out.write("                <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                <p>Sliders</p>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a href=\"pages/UI/modals.html\" class=\"nav-link\">\r\n");
      out.write("                <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                <p>Modals & Alerts</p>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a href=\"pages/UI/navbar.html\" class=\"nav-link\">\r\n");
      out.write("                <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                <p>Navbar & Tabs</p>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a href=\"pages/UI/timeline.html\" class=\"nav-link\">\r\n");
      out.write("                <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                <p>Timeline</p>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a href=\"pages/UI/ribbons.html\" class=\"nav-link\">\r\n");
      out.write("                <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                <p>Ribbons</p>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a href=\"#\" class=\"nav-link\">\r\n");
      out.write("            <i class=\"nav-icon fas fa-edit\"></i>\r\n");
      out.write("            <p>\r\n");
      out.write("              Forms\r\n");
      out.write("              <i class=\"fas fa-angle-left right\"></i>\r\n");
      out.write("            </p>\r\n");
      out.write("          </a>\r\n");
      out.write("          <ul class=\"nav nav-treeview\">\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a href=\"pages/forms/general.html\" class=\"nav-link\">\r\n");
      out.write("                <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                <p>General Elements</p>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a href=\"pages/forms/advanced.html\" class=\"nav-link\">\r\n");
      out.write("                <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                <p>Advanced Elements</p>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a href=\"pages/forms/editors.html\" class=\"nav-link\">\r\n");
      out.write("                <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                <p>Editors</p>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a href=\"pages/forms/validation.html\" class=\"nav-link\">\r\n");
      out.write("                <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                <p>Validation</p>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a href=\"#\" class=\"nav-link\">\r\n");
      out.write("            <i class=\"nav-icon fas fa-table\"></i>\r\n");
      out.write("            <p>\r\n");
      out.write("              Tables\r\n");
      out.write("              <i class=\"fas fa-angle-left right\"></i>\r\n");
      out.write("            </p>\r\n");
      out.write("          </a>\r\n");
      out.write("          <ul class=\"nav nav-treeview\">\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a href=\"pages/tables/simple.html\" class=\"nav-link\">\r\n");
      out.write("                <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                <p>Simple Tables</p>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a href=\"pages/tables/data.html\" class=\"nav-link\">\r\n");
      out.write("                <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                <p>DataTables</p>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a href=\"pages/tables/jsgrid.html\" class=\"nav-link\">\r\n");
      out.write("                <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                <p>jsGrid</p>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-header\">EXAMPLES</li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a href=\"pages/calendar.html\" class=\"nav-link\">\r\n");
      out.write("            <i class=\"nav-icon far fa-calendar-alt\"></i>\r\n");
      out.write("            <p>\r\n");
      out.write("              Calendar\r\n");
      out.write("              <span class=\"badge badge-info right\">2</span>\r\n");
      out.write("            </p>\r\n");
      out.write("          </a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a href=\"pages/gallery.html\" class=\"nav-link\">\r\n");
      out.write("            <i class=\"nav-icon far fa-image\"></i>\r\n");
      out.write("            <p>\r\n");
      out.write("              Gallery\r\n");
      out.write("            </p>\r\n");
      out.write("          </a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a href=\"pages/kanban.html\" class=\"nav-link\">\r\n");
      out.write("            <i class=\"nav-icon fas fa-columns\"></i>\r\n");
      out.write("            <p>\r\n");
      out.write("              Kanban Board\r\n");
      out.write("            </p>\r\n");
      out.write("          </a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a href=\"#\" class=\"nav-link\">\r\n");
      out.write("            <i class=\"nav-icon far fa-envelope\"></i>\r\n");
      out.write("            <p>\r\n");
      out.write("              Mailbox\r\n");
      out.write("              <i class=\"fas fa-angle-left right\"></i>\r\n");
      out.write("            </p>\r\n");
      out.write("          </a>\r\n");
      out.write("          <ul class=\"nav nav-treeview\">\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a href=\"pages/mailbox/mailbox.html\" class=\"nav-link\">\r\n");
      out.write("                <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                <p>Inbox</p>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a href=\"pages/mailbox/compose.html\" class=\"nav-link\">\r\n");
      out.write("                <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                <p>Compose</p>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a href=\"pages/mailbox/read-mail.html\" class=\"nav-link\">\r\n");
      out.write("                <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                <p>Read</p>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a href=\"#\" class=\"nav-link\">\r\n");
      out.write("            <i class=\"nav-icon fas fa-book\"></i>\r\n");
      out.write("            <p>\r\n");
      out.write("              Pages\r\n");
      out.write("              <i class=\"fas fa-angle-left right\"></i>\r\n");
      out.write("            </p>\r\n");
      out.write("          </a>\r\n");
      out.write("          <ul class=\"nav nav-treeview\">\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a href=\"pages/examples/invoice.html\" class=\"nav-link\">\r\n");
      out.write("                <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                <p>Invoice</p>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a href=\"pages/examples/profile.html\" class=\"nav-link\">\r\n");
      out.write("                <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                <p>Profile</p>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a href=\"pages/examples/e-commerce.html\" class=\"nav-link\">\r\n");
      out.write("                <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                <p>E-commerce</p>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a href=\"pages/examples/projects.html\" class=\"nav-link\">\r\n");
      out.write("                <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                <p>Projects</p>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a href=\"pages/examples/project-add.html\" class=\"nav-link\">\r\n");
      out.write("                <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                <p>Project Add</p>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a href=\"pages/examples/project-edit.html\" class=\"nav-link\">\r\n");
      out.write("                <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                <p>Project Edit</p>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a href=\"pages/examples/project-detail.html\" class=\"nav-link\">\r\n");
      out.write("                <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                <p>Project Detail</p>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a href=\"pages/examples/contacts.html\" class=\"nav-link\">\r\n");
      out.write("                <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                <p>Contacts</p>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a href=\"pages/examples/faq.html\" class=\"nav-link\">\r\n");
      out.write("                <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                <p>FAQ</p>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a href=\"pages/examples/contact-us.html\" class=\"nav-link\">\r\n");
      out.write("                <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                <p>Contact us</p>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a href=\"#\" class=\"nav-link\">\r\n");
      out.write("            <i class=\"nav-icon far fa-plus-square\"></i>\r\n");
      out.write("            <p>\r\n");
      out.write("              Extras\r\n");
      out.write("              <i class=\"fas fa-angle-left right\"></i>\r\n");
      out.write("            </p>\r\n");
      out.write("          </a>\r\n");
      out.write("          <ul class=\"nav nav-treeview\">\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a href=\"#\" class=\"nav-link\">\r\n");
      out.write("                <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                <p>\r\n");
      out.write("                  Login & Register v1\r\n");
      out.write("                  <i class=\"fas fa-angle-left right\"></i>\r\n");
      out.write("                </p>\r\n");
      out.write("              </a>\r\n");
      out.write("              <ul class=\"nav nav-treeview\">\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                  <a href=\"pages/examples/login.html\" class=\"nav-link\">\r\n");
      out.write("                    <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                    <p>Login v1</p>\r\n");
      out.write("                  </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                  <a href=\"pages/examples/register.html\" class=\"nav-link\">\r\n");
      out.write("                    <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                    <p>Register v1</p>\r\n");
      out.write("                  </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                  <a href=\"pages/examples/forgot-password.html\" class=\"nav-link\">\r\n");
      out.write("                    <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                    <p>Forgot Password v1</p>\r\n");
      out.write("                  </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                  <a href=\"pages/examples/recover-password.html\" class=\"nav-link\">\r\n");
      out.write("                    <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                    <p>Recover Password v1</p>\r\n");
      out.write("                  </a>\r\n");
      out.write("                </li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a href=\"#\" class=\"nav-link\">\r\n");
      out.write("                <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                <p>\r\n");
      out.write("                  Login & Register v2\r\n");
      out.write("                  <i class=\"fas fa-angle-left right\"></i>\r\n");
      out.write("                </p>\r\n");
      out.write("              </a>\r\n");
      out.write("              <ul class=\"nav nav-treeview\">\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                  <a href=\"pages/examples/login-v2.html\" class=\"nav-link\">\r\n");
      out.write("                    <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                    <p>Login v2</p>\r\n");
      out.write("                  </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                  <a href=\"pages/examples/register-v2.html\" class=\"nav-link\">\r\n");
      out.write("                    <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                    <p>Register v2</p>\r\n");
      out.write("                  </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                  <a href=\"pages/examples/forgot-password-v2.html\" class=\"nav-link\">\r\n");
      out.write("                    <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                    <p>Forgot Password v2</p>\r\n");
      out.write("                  </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                  <a href=\"pages/examples/recover-password-v2.html\" class=\"nav-link\">\r\n");
      out.write("                    <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                    <p>Recover Password v2</p>\r\n");
      out.write("                  </a>\r\n");
      out.write("                </li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a href=\"pages/examples/lockscreen.html\" class=\"nav-link\">\r\n");
      out.write("                <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                <p>Lockscreen</p>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a href=\"pages/examples/legacy-user-menu.html\" class=\"nav-link\">\r\n");
      out.write("                <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                <p>Legacy User Menu</p>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a href=\"pages/examples/language-menu.html\" class=\"nav-link\">\r\n");
      out.write("                <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                <p>Language Menu</p>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a href=\"pages/examples/404.html\" class=\"nav-link\">\r\n");
      out.write("                <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                <p>Error 404</p>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a href=\"pages/examples/500.html\" class=\"nav-link\">\r\n");
      out.write("                <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                <p>Error 500</p>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a href=\"pages/examples/pace.html\" class=\"nav-link\">\r\n");
      out.write("                <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                <p>Pace</p>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a href=\"pages/examples/blank.html\" class=\"nav-link\">\r\n");
      out.write("                <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                <p>Blank Page</p>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a href=\"starter.html\" class=\"nav-link\">\r\n");
      out.write("                <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                <p>Starter Page</p>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a href=\"#\" class=\"nav-link\">\r\n");
      out.write("            <i class=\"nav-icon fas fa-search\"></i>\r\n");
      out.write("            <p>\r\n");
      out.write("              Search\r\n");
      out.write("              <i class=\"fas fa-angle-left right\"></i>\r\n");
      out.write("            </p>\r\n");
      out.write("          </a>\r\n");
      out.write("          <ul class=\"nav nav-treeview\">\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a href=\"pages/search/simple.html\" class=\"nav-link\">\r\n");
      out.write("                <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                <p>Simple Search</p>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a href=\"pages/search/enhanced.html\" class=\"nav-link\">\r\n");
      out.write("                <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                <p>Enhanced</p>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-header\">MISCELLANEOUS</li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a href=\"iframe.html\" class=\"nav-link\">\r\n");
      out.write("            <i class=\"nav-icon fas fa-ellipsis-h\"></i>\r\n");
      out.write("            <p>Tabbed IFrame Plugin</p>\r\n");
      out.write("          </a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a href=\"https://adminlte.io/docs/3.1/\" class=\"nav-link\">\r\n");
      out.write("            <i class=\"nav-icon fas fa-file\"></i>\r\n");
      out.write("            <p>Documentation</p>\r\n");
      out.write("          </a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-header\">MULTI LEVEL EXAMPLE</li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a href=\"#\" class=\"nav-link\">\r\n");
      out.write("            <i class=\"fas fa-circle nav-icon\"></i>\r\n");
      out.write("            <p>Level 1</p>\r\n");
      out.write("          </a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a href=\"#\" class=\"nav-link\">\r\n");
      out.write("            <i class=\"nav-icon fas fa-circle\"></i>\r\n");
      out.write("            <p>\r\n");
      out.write("              Level 1\r\n");
      out.write("              <i class=\"right fas fa-angle-left\"></i>\r\n");
      out.write("            </p>\r\n");
      out.write("          </a>\r\n");
      out.write("          <ul class=\"nav nav-treeview\">\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a href=\"#\" class=\"nav-link\">\r\n");
      out.write("                <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                <p>Level 2</p>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a href=\"#\" class=\"nav-link\">\r\n");
      out.write("                <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                <p>\r\n");
      out.write("                  Level 2\r\n");
      out.write("                  <i class=\"right fas fa-angle-left\"></i>\r\n");
      out.write("                </p>\r\n");
      out.write("              </a>\r\n");
      out.write("              <ul class=\"nav nav-treeview\">\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                  <a href=\"#\" class=\"nav-link\">\r\n");
      out.write("                    <i class=\"far fa-dot-circle nav-icon\"></i>\r\n");
      out.write("                    <p>Level 3</p>\r\n");
      out.write("                  </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                  <a href=\"#\" class=\"nav-link\">\r\n");
      out.write("                    <i class=\"far fa-dot-circle nav-icon\"></i>\r\n");
      out.write("                    <p>Level 3</p>\r\n");
      out.write("                  </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                  <a href=\"#\" class=\"nav-link\">\r\n");
      out.write("                    <i class=\"far fa-dot-circle nav-icon\"></i>\r\n");
      out.write("                    <p>Level 3</p>\r\n");
      out.write("                  </a>\r\n");
      out.write("                </li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a href=\"#\" class=\"nav-link\">\r\n");
      out.write("                <i class=\"far fa-circle nav-icon\"></i>\r\n");
      out.write("                <p>Level 2</p>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a href=\"#\" class=\"nav-link\">\r\n");
      out.write("            <i class=\"fas fa-circle nav-icon\"></i>\r\n");
      out.write("            <p>Level 1</p>\r\n");
      out.write("          </a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-header\">LABELS</li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a href=\"#\" class=\"nav-link\">\r\n");
      out.write("            <i class=\"nav-icon far fa-circle text-danger\"></i>\r\n");
      out.write("            <p class=\"text\">Important</p>\r\n");
      out.write("          </a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a href=\"#\" class=\"nav-link\">\r\n");
      out.write("            <i class=\"nav-icon far fa-circle text-warning\"></i>\r\n");
      out.write("            <p>Warning</p>\r\n");
      out.write("          </a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a href=\"#\" class=\"nav-link\">\r\n");
      out.write("            <i class=\"nav-icon far fa-circle text-info\"></i>\r\n");
      out.write("            <p>Informational</p>\r\n");
      out.write("          </a>\r\n");
      out.write("        </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </nav>\r\n");
      out.write("    <!-- /.sidebar-menu -->\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- /.sidebar -->\r\n");
      out.write("</aside>\r\n");
      out.write("<!-- Content Wrapper. Contains page content -->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_sec_005fauthorize_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_sec_005fauthorize_005f0 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    boolean _jspx_th_sec_005fauthorize_005f0_reused = false;
    try {
      _jspx_th_sec_005fauthorize_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthorize_005f0.setParent(null);
      // /WEB-INF/views/tiles/aside.jsp(16,4) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthorize_005f0.setAccess("isAnonymous()");
      int _jspx_eval_sec_005fauthorize_005f0 = _jspx_th_sec_005fauthorize_005f0.doStartTag();
      if (_jspx_eval_sec_005fauthorize_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\r\n");
        out.write("    <div class=\"user-panel mt-3 pb-3 mb-3 d-flex\">\r\n");
        out.write("	      <div class=\"image\">\r\n");
        out.write("	        	<img src=\"/resources/adminlte/dist/img/user2-160x160.jpg\" class=\"img-circle elevation-2\" alt=\"User Image\">\r\n");
        out.write("	      </div>\r\n");
        out.write("	      <div class=\"info\">\r\n");
        out.write("	      		<a href=\"#\" class=\"d-block\">Alexander Pierce</a>\r\n");
        out.write("	      </div>\r\n");
        out.write("      </div>\r\n");
        out.write("      ");
      }
      if (_jspx_th_sec_005fauthorize_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.reuse(_jspx_th_sec_005fauthorize_005f0);
      _jspx_th_sec_005fauthorize_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthorize_005f0, _jsp_getInstanceManager(), _jspx_th_sec_005fauthorize_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthorize_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_sec_005fauthorize_005f1 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    boolean _jspx_th_sec_005fauthorize_005f1_reused = false;
    try {
      _jspx_th_sec_005fauthorize_005f1.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthorize_005f1.setParent(null);
      // /WEB-INF/views/tiles/aside.jsp(27,2) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthorize_005f1.setAccess("isAuthenticated()");
      int _jspx_eval_sec_005fauthorize_005f1 = _jspx_th_sec_005fauthorize_005f1.doStartTag();
      if (_jspx_eval_sec_005fauthorize_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\r\n");
        out.write("		 <div class=\"user-panel mt-3 pb-3 mb-3 d-flex\">\r\n");
        out.write("							   <div class=\"image\">\r\n");
        out.write("						      	  <img src=\"/resources/upload/");
        if (_jspx_meth_sec_005fauthentication_005f0(_jspx_th_sec_005fauthorize_005f1, _jspx_page_context))
          return true;
        out.write(".jpg\" \r\n");
        out.write("						      	  class=\"img-circle elevation-2\" alt=\"User Image\">\r\n");
        out.write("						      </div>\r\n");
        out.write("						      <div class=\"info\">\r\n");
        out.write("				        		<a href=\"#\" class=\"d-block\">\r\n");
        out.write("				        		");
        if (_jspx_meth_sec_005fauthentication_005f1(_jspx_th_sec_005fauthorize_005f1, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("				        		(");
        if (_jspx_meth_sec_005fauthentication_005f2(_jspx_th_sec_005fauthorize_005f1, _jspx_page_context))
          return true;
        out.write(")님 환영합니다\r\n");
        out.write("        						<form action=\"/logout\" method=\"post\">\r\n");
        out.write("									<button type=\"submit\" class=\"btn btn-primary\"\r\n");
        out.write("											style=\"-bs-btn-padding-y: .25rem; - -bs-btn-padding-x: .5rem; - -bs-btn-font-size: .75rem;\">\r\n");
        out.write("											로그아웃\r\n");
        out.write("									</button>\r\n");
        out.write("											");
        if (_jspx_meth_sec_005fcsrfInput_005f0(_jspx_th_sec_005fauthorize_005f1, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("								</form>\r\n");
        out.write("				        		</a>\r\n");
        out.write("			        	</div>\r\n");
        out.write("			      </div>\r\n");
        out.write("    		");
      }
      if (_jspx_th_sec_005fauthorize_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.reuse(_jspx_th_sec_005fauthorize_005f1);
      _jspx_th_sec_005fauthorize_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthorize_005f1, _jsp_getInstanceManager(), _jspx_th_sec_005fauthorize_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthentication_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_sec_005fauthorize_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authentication
    org.springframework.security.taglibs.authz.AuthenticationTag _jspx_th_sec_005fauthentication_005f0 = (org.springframework.security.taglibs.authz.AuthenticationTag) _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody.get(org.springframework.security.taglibs.authz.AuthenticationTag.class);
    boolean _jspx_th_sec_005fauthentication_005f0_reused = false;
    try {
      _jspx_th_sec_005fauthentication_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthentication_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sec_005fauthorize_005f1);
      // /WEB-INF/views/tiles/aside.jsp(30,43) name = property type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthentication_005f0.setProperty("principal.memberVO.memId");
      int _jspx_eval_sec_005fauthentication_005f0 = _jspx_th_sec_005fauthentication_005f0.doStartTag();
      if (_jspx_th_sec_005fauthentication_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody.reuse(_jspx_th_sec_005fauthentication_005f0);
      _jspx_th_sec_005fauthentication_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthentication_005f0, _jsp_getInstanceManager(), _jspx_th_sec_005fauthentication_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthentication_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_sec_005fauthorize_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authentication
    org.springframework.security.taglibs.authz.AuthenticationTag _jspx_th_sec_005fauthentication_005f1 = (org.springframework.security.taglibs.authz.AuthenticationTag) _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody.get(org.springframework.security.taglibs.authz.AuthenticationTag.class);
    boolean _jspx_th_sec_005fauthentication_005f1_reused = false;
    try {
      _jspx_th_sec_005fauthentication_005f1.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthentication_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sec_005fauthorize_005f1);
      // /WEB-INF/views/tiles/aside.jsp(35,14) name = property type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthentication_005f1.setProperty("principal.memberVO.memName");
      int _jspx_eval_sec_005fauthentication_005f1 = _jspx_th_sec_005fauthentication_005f1.doStartTag();
      if (_jspx_th_sec_005fauthentication_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody.reuse(_jspx_th_sec_005fauthentication_005f1);
      _jspx_th_sec_005fauthentication_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthentication_005f1, _jsp_getInstanceManager(), _jspx_th_sec_005fauthentication_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthentication_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_sec_005fauthorize_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authentication
    org.springframework.security.taglibs.authz.AuthenticationTag _jspx_th_sec_005fauthentication_005f2 = (org.springframework.security.taglibs.authz.AuthenticationTag) _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody.get(org.springframework.security.taglibs.authz.AuthenticationTag.class);
    boolean _jspx_th_sec_005fauthentication_005f2_reused = false;
    try {
      _jspx_th_sec_005fauthentication_005f2.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthentication_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sec_005fauthorize_005f1);
      // /WEB-INF/views/tiles/aside.jsp(36,15) name = property type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthentication_005f2.setProperty("principal.memberVO.memId");
      int _jspx_eval_sec_005fauthentication_005f2 = _jspx_th_sec_005fauthentication_005f2.doStartTag();
      if (_jspx_th_sec_005fauthentication_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody.reuse(_jspx_th_sec_005fauthentication_005f2);
      _jspx_th_sec_005fauthentication_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthentication_005f2, _jsp_getInstanceManager(), _jspx_th_sec_005fauthentication_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fcsrfInput_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_sec_005fauthorize_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:csrfInput
    org.springframework.security.taglibs.csrf.CsrfInputTag _jspx_th_sec_005fcsrfInput_005f0 = (org.springframework.security.taglibs.csrf.CsrfInputTag) _005fjspx_005ftagPool_005fsec_005fcsrfInput_005fnobody.get(org.springframework.security.taglibs.csrf.CsrfInputTag.class);
    boolean _jspx_th_sec_005fcsrfInput_005f0_reused = false;
    try {
      _jspx_th_sec_005fcsrfInput_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fcsrfInput_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sec_005fauthorize_005f1);
      int _jspx_eval_sec_005fcsrfInput_005f0 = _jspx_th_sec_005fcsrfInput_005f0.doStartTag();
      if (_jspx_th_sec_005fcsrfInput_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fcsrfInput_005fnobody.reuse(_jspx_th_sec_005fcsrfInput_005f0);
      _jspx_th_sec_005fcsrfInput_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fcsrfInput_005f0, _jsp_getInstanceManager(), _jspx_th_sec_005fcsrfInput_005f0_reused);
    }
    return false;
  }
}
