/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.83
 * Generated at: 2022-11-21 06:05:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.gallery;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class regist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1666247059863L));
    _jspx_dependants.put("jar:file:/C:/eGovFrameDev-3.10.0-64bit/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/egovProj/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"/resources/ckeditor/ckeditor.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/resources/js/jquery-3.6.0.js\"></script>\r\n");
      out.write("<script src=\"/resources/adminlte/plugins/sweetalert2/sweetalert2.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/adminlte/plugins/sweetalert2-theme-bootstrap-4/bootstrap-4.min.css\">\r\n");
      out.write("<section class=\"content\">\r\n");
      out.write("	<div class=\"row\">\r\n");
      out.write("		<div class=\"col-md-6\">\r\n");
      out.write("			<div class=\"card card-primary\">\r\n");
      out.write("				<div class=\"card-header\">\r\n");
      out.write("					<h3 class=\"card-title\">도서정보</h3>\r\n");
      out.write("					<input type=\"text\" name=\"bookId\" id=\"bookId\" />\r\n");
      out.write("					<div class=\"card-tools\">\r\n");
      out.write("						<button type=\"button\" class=\"btn btn-tool\"\r\n");
      out.write("							data-card-widget=\"collapse\" title=\"Collapse\">\r\n");
      out.write("							<i class=\"fas fa-minus\"></i>\r\n");
      out.write("						</button>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"card-body\">\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("						<div style=\"clear: both;\">\r\n");
      out.write("							<label for=\"title\">제목</label>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div style=\"width: 70%; float: left;\">\r\n");
      out.write("							<input type=\"text\" id=\"title\" name=\"title\" class=\"form-control\" readonly/>\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- \r\n");
      out.write("1) button\r\n");
      out.write("	data-toggle=\"modal\" data-target=\"샵modal-lg\"\r\n");
      out.write("2) a\r\n");
      out.write("	data-toggle=\"modal\" href=\"샵modal-lg\"\r\n");
      out.write("3) 기타\r\n");
      out.write("	data-toggle=\"modal\" data-target=\"샵modal-lg\"\r\n");
      out.write(" -->\r\n");
      out.write("						<div style=\"width: 30%; float: right;\">\r\n");
      out.write("							<button type=\"button\"\r\n");
      out.write("								class=\"btn btn-outline-info btn-block btn-flat\"\r\n");
      out.write("								data-toggle=\"modal\" data-target=\"#modal-lg\">\r\n");
      out.write("								<i class=\"fa fa-book\"></i>책 검색\r\n");
      out.write("							</button>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("						<label for=\"category\">카테고리</label> <select id=\"category\"\r\n");
      out.write("							name=\"category\" class=\"form-control custom-select\" disabled>\r\n");
      out.write("							<option value=\"a0101\" selected>소설</option>\r\n");
      out.write("							<option value=\"a0102\">에세이</option>\r\n");
      out.write("							<option value=\"a0103\">어린이</option>\r\n");
      out.write("							<option value=\"a0104\">요리</option>\r\n");
      out.write("							<option value=\"a0105\">수험서</option>\r\n");
      out.write("							<option value=\"a0106\">자격증</option>\r\n");
      out.write("						</select>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("						<label for=\"price\">가격</label> <input type=\"text\" id=\"price\"\r\n");
      out.write("							name=\"price\" class=\"form-control\" readonly />\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("						<label for=\"insertDate\">입력 일자</label> <input type=\"text\"\r\n");
      out.write("							id=\"insertDate\" name=\"insertDate\" class=\"form-control\" readonly/>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("						<label for=\"content\">책 내용</label>\r\n");
      out.write("						<textarea id=\"content\" name=\"content\" class=\"form-control\"\r\n");
      out.write("							rows=\"4\" readonly></textarea>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"col-md-6\">\r\n");
      out.write("			<div class=\"card card-secondary\">\r\n");
      out.write("				<div class=\"card-header\">\r\n");
      out.write("					<h3 class=\"card-title\">이미지 정보</h3>\r\n");
      out.write("					<div class=\"card-tools\">\r\n");
      out.write("						<button type=\"button\" class=\"btn btn-tool\"\r\n");
      out.write("							data-card-widget=\"collapse\" title=\"Collapse\">\r\n");
      out.write("							<i class=\"fas fa-minus\"></i>\r\n");
      out.write("						</button>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- 미리보기 이미지 보이기 시작 -->\r\n");
      out.write("				<div class=\"card-body\" id=\"card-images\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- 미리보기 이미지 보이기 끝 -->\r\n");
      out.write("				<div class=\"card-footer\">\r\n");
      out.write("					<div class=\"input-group\">\r\n");
      out.write("							<div class=\"custom-file\">\r\n");
      out.write("								<input type=\"file\" name=\"uploadFile\" id=\"input_imgs\" class=\"custom-file-input\" multiple=\"multiple\" disabled/>\r\n");
      out.write("								<label class=\"custom-file-label\" for=\"exampleInputFile\">Choose file</label>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"input-group-append\">\r\n");
      out.write("								<span class=\"input-group-text\" id=\"uploadBtn\" style=\"cursor:pointer;\">Upload</span>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"row\">\r\n");
      out.write("		<div class=\"col-12\">\r\n");
      out.write("			<a href=\"#\" class=\"btn btn-secondary\">Cancel</a> <input type=\"submit\"\r\n");
      out.write("				value=\"Create new Project\" class=\"btn btn-success float-right\">\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</section>\r\n");
      out.write("<!-- 책 검색 모달 시작 -->\r\n");
      out.write("<div class=\"modal fade\" id=\"modal-lg\" style=\"display: none;\"\r\n");
      out.write("	aria-hidden=\"true\">\r\n");
      out.write("	<div class=\"modal-dialog modal-lg\">\r\n");
      out.write("		<div class=\"modal-content\">\r\n");
      out.write("			<div class=\"modal-header\">\r\n");
      out.write("				<h4 class=\"modal-title\">책 검색</h4>\r\n");
      out.write("				<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("					aria-label=\"Close\">\r\n");
      out.write("					<span aria-hidden=\"true\">×</span>\r\n");
      out.write("				</button>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"modal-body\">\r\n");
      out.write("				<!-- 검색 영역 시작 -->\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("					<div class=\"col-md-8 offset-md-2\">\r\n");
      out.write("							<div class=\"input-group\">\r\n");
      out.write("								<input type=\"text\" class=\"form-control form-control-lg\"\r\n");
      out.write("									placeholder=\"Type your keywords here\">\r\n");
      out.write("								<div class=\"input-group-append\">\r\n");
      out.write("									<button type=\"button\" id=\"btnSearch\" class=\"btn btn-lg btn-default\">\r\n");
      out.write("										<i class=\"fa fa-search\"></i>\r\n");
      out.write("									</button>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- 검색 영역 끝 -->\r\n");
      out.write("				<!-- 결과 영역 시작 -->\r\n");
      out.write("				<div class=\"row mt-3\">\r\n");
      out.write("					<div class=\"col-md-10 offset-md-1\">\r\n");
      out.write("						<div class=\"list-group\">\r\n");
      out.write("<!-- 							<div class=\"list-group-item\"> -->\r\n");
      out.write("<!-- 								<div class=\"row\"> -->\r\n");
      out.write("<!-- 									<div class=\"col-auto\"> -->\r\n");
      out.write("<!-- 										<img class=\"img-fluid\" src=\"../../dist/img/photo1.png\" -->\r\n");
      out.write("<!-- 											alt=\"Photo\" style=\"max-height: 160px;\"> -->\r\n");
      out.write("<!-- 									</div> -->\r\n");
      out.write("<!-- 									<div class=\"col px-4\"> -->\r\n");
      out.write("<!-- 										<div> -->\r\n");
      out.write("<!-- 											<div class=\"float-right\">2021-04-20 10:14pm</div> -->\r\n");
      out.write("<!-- 											<h3>Lorem ipsum dolor sit amet</h3> -->\r\n");
      out.write("<!-- 											<p class=\"mb-0\">consectetuer adipiscing elit. Aenean -->\r\n");
      out.write("<!-- 												commodo ligula eget dolor. Aenean massa. Cum sociis natoque -->\r\n");
      out.write("<!-- 												penatibus et magnis dis parturient montes, nascetur -->\r\n");
      out.write("<!-- 												ridiculus mus.</p> -->\r\n");
      out.write("<!-- 										</div> -->\r\n");
      out.write("<!-- 									</div> -->\r\n");
      out.write("<!-- 								</div> -->\r\n");
      out.write("<!-- 							</div> -->\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- 결과 영역 끝 -->\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"modal-footer <!--justify-content-between-->\">\r\n");
      out.write("				<button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- 책 검색 모달 끝 -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("CKEDITOR.replace(\"content\");\r\n");
      out.write("let bookVOList;\r\n");
      out.write("\r\n");
      out.write("//이미지 미리보기 시작/////////////////////////////\r\n");
      out.write("//이미지 객체를 담을 배열\r\n");
      out.write("let sel_file = [];\r\n");
      out.write("$(function(){\r\n");
      out.write("		var Toast = Swal.mixin({\r\n");
      out.write("	        toast: true,\r\n");
      out.write("	        position: 'top-end',\r\n");
      out.write("	        showConfirmButton: false,\r\n");
      out.write("	        timer: 3000\r\n");
      out.write("	      });\r\n");
      out.write("	  \r\n");
      out.write("	$(\"#input_imgs\").on(\"change\",handleImgFileSelect);\r\n");
      out.write("	//e : onchange 이벤트 객체\r\n");
      out.write("	function handleImgFileSelect(e){\r\n");
      out.write("		//e.target : <input type=\"file\"\r\n");
      out.write("		let files = e.target.files;\r\n");
      out.write("		//이미지 오브젝트 배열\r\n");
      out.write("		let fileArr = Array.prototype.slice.call(files);\r\n");
      out.write("		\r\n");
      out.write("		//f : 이미지 파일\r\n");
      out.write("		fileArr.forEach(function(f){\r\n");
      out.write("			if(!f.type.match(\"image.*\")){\r\n");
      out.write("				alert(\"이미지 확장자만 가능합니다.\");\r\n");
      out.write("				//함수 종료\r\n");
      out.write("				return;\r\n");
      out.write("			}\r\n");
      out.write("			//이미지를 배열에 넣음\r\n");
      out.write("			sel_file.push(f);\r\n");
      out.write("			//이미지를 읽어보자\r\n");
      out.write("			let reader = new FileReader();\r\n");
      out.write("			//e : 리더가 이미지를 읽을 때 그 이벤트\r\n");
      out.write("			reader.onload = function(e){\r\n");
      out.write("				//e.target : 이미지 객체\r\n");
      out.write("				let img_html = \"<img src=\\\"\" + e.target.result + \"\\\" style='width:50%;' />\";\r\n");
      out.write("				//객체.append : 누적, .html : 새로고침, innerHTML : J/S\r\n");
      out.write("				$(\"#card-images\").append(img_html);\r\n");
      out.write("			}\r\n");
      out.write("			//다음 이미지 파일(f)을 위해 리더를 초기화\r\n");
      out.write("			reader.readAsDataURL(f);\r\n");
      out.write("		});\r\n");
      out.write("	}\r\n");
      out.write("	//이미지 미리보기 끝/////////////////////////////\r\n");
      out.write("	\r\n");
      out.write("	//ajax 파일 업로드 시작////////////////////////////////////\r\n");
      out.write("	//e : event\r\n");
      out.write("	$(\"#uploadBtn\").on(\"click\",function(e){\r\n");
      out.write("		//가상 폼(이미지들을 넣자)\r\n");
      out.write("		let formData = new FormData();\r\n");
      out.write("		let inputFile = $(\"input[name='uploadFile']\");\r\n");
      out.write("		//파일들을 변수에 담음\r\n");
      out.write("		let files = inputFile[0].files;\r\n");
      out.write("		\r\n");
      out.write("		console.log(\"files : \" + files);\r\n");
      out.write("		\r\n");
      out.write("		//가상폼인 formdata에 각각의 이미지를 넣어보자\r\n");
      out.write("		for(let i=0;i<files.length;i++){\r\n");
      out.write("			//uploadFile[]\r\n");
      out.write("			formData.append(\"uploadFile\",files[i]);\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		let bookId = $(\"#bookId\").val();\r\n");
      out.write("		console.log(\"bookId : \" + bookId);\r\n");
      out.write("		//ATTACH 테이블의 user_no 컬럼의 데이터에는 bookId가 들어가야 한다\r\n");
      out.write("/*\r\n");
      out.write("		<form>\r\n");
      out.write("					<input type=\"file\" name=\"uploadFile\"..\r\n");
      out.write("					<input type=\"file\" name=\"uploadFile\"..\r\n");
      out.write("					<input type=\"file\" name=\"uploadFile\"..\r\n");
      out.write("					<input type=\"text\" name=\"bookId\"..\r\n");
      out.write(" 		</form>\r\n");
      out.write("*/\r\n");
      out.write("		formData.append(\"bookId\", bookId)\r\n");
      out.write("		\r\n");
      out.write("	\r\n");
      out.write("		//아작났어유 피씨다타써\r\n");
      out.write("		//dataType : 응답데이터 타입\r\n");
      out.write("		////upload/uploadAjaxAction 참고\r\n");
      out.write("		//ATTACH 테이블의 user_no 컬럼의 데이터에는 bookId가 들어가야 한다\r\n");
      out.write("		//ATTACH 테이블의 seq 컬럼의 데이터는 1부터 1씩 자동 증가\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			url:\"/gallery/uploadAjaxAction\",\r\n");
      out.write("			processData:false,\r\n");
      out.write("			contentType:false,\r\n");
      out.write("			data:formData,\r\n");
      out.write("			dataType:\"json\",\r\n");
      out.write("			type:\"post\",\r\n");
      out.write("			\r\n");
      out.write("			success:function(result){\r\n");
      out.write("				console.log(\"result : \" + JSON.stringify(result));\r\n");
      out.write("				\r\n");
      out.write("				console.log(\"result.bookId : \" + result.bookId);\r\n");
      out.write("				console.log(\"result.status : \" + result.status);\r\n");
      out.write("				\r\n");
      out.write("				if(result.status>0){ //다중 insert성공\r\n");
      out.write("				   Toast.fire({\r\n");
      out.write("				      icon:'success',\r\n");
      out.write("				      title:'뎀'\r\n");
      out.write("				   });\r\n");
      out.write("				//3초 후에 이동\r\n");
      out.write("				setTimeout(function(){\r\n");
      out.write("					location.href = \"/gallery/list?bookId=\"+result.bookId;\r\n");
      out.write("				},3000);\r\n");
      out.write("				}else{ // 다중 insert 실패\\\r\n");
      out.write("					  Toast.fire({\r\n");
      out.write("					      icon:'error',\r\n");
      out.write("					      title:'안뎀'\r\n");
      out.write("					   });\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("		})\r\n");
      out.write("	});\r\n");
      out.write("	//ajax 파일 업로드 끝////////////////////////////////////\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	$(\"#btnSearch\").on(\"click\",function(){\r\n");
      out.write("		let str = $(\".form-control-lg\").val();\r\n");
      out.write("		\r\n");
      out.write("		let data = {\"title\":str};\r\n");
      out.write("		console.log(\"data : \" + JSON.stringify(str));\r\n");
      out.write("		\r\n");
      out.write("		//스프링 시큐리티를 위한 토큰 처리(csrf) -> 불토엔 큰 코스로 픽스!\r\n");
      out.write("		let header = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.headerName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("		let token = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.token}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("		\r\n");
      out.write("		console.log(\"header : \" + header + \", token : \" + token);\r\n");
      out.write("		\r\n");
      out.write("		//아작났어유..피씨다타써\r\n");
      out.write("		//contentType : 가즈아\r\n");
      out.write("		//dataType : 드루와\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			url:\"/gallery/registPost\",\r\n");
      out.write("			contentType:\"application/json;charset=utf-8\",\r\n");
      out.write("			data:JSON.stringify(data),\r\n");
      out.write("			dataType:\"json\",\r\n");
      out.write("			type:\"post\",\r\n");
      out.write("			beforeSend: function(xhr){\r\n");
      out.write("				xhr.setRequestHeader(header,token);\r\n");
      out.write("			},\r\n");
      out.write("			success:function(result){\r\n");
      out.write("// 				console.log(\"result : \" + JSON.stringify(result));\r\n");
      out.write("				//전역 변수에 넣음\r\n");
      out.write("				bookVOList = result;\r\n");
      out.write("				$(\".list-group\").children().remove();\r\n");
      out.write("				$.each(result,function(index,item){\r\n");
      out.write("					console.log(\"bookId : \" + item.bookId);\r\n");
      out.write("					console.log(\"title : \" + item.title);\r\n");
      out.write("					//result => List<BookVO>, item => BookVO\r\n");
      out.write("					//volist => List<AttachVO>\r\n");
      out.write("					let volist = item.attachVOList;\r\n");
      out.write("					let filename = \"/noimage.jpg\";\r\n");
      out.write("					if(volist.length>0){\r\n");
      out.write("						console.log(\"attachVOList : \" + item.attachVOList);\r\n");
      out.write("						//volist => List<AttachVO>, item => AttachVO\r\n");
      out.write("						$.each(volist,function(index,item){\r\n");
      out.write("							//책 이미지가 1 이상이면 이미지 경로를 변수에 대입\r\n");
      out.write("							filename = item.filename;\r\n");
      out.write("						});\r\n");
      out.write("					}\r\n");
      out.write("					\r\n");
      out.write("					console.log(\"filename : \" + filename);\r\n");
      out.write("					\r\n");
      out.write("					let dt = new Date(item.insertDate);\r\n");
      out.write("					let dtYY = dt.getFullYear();\r\n");
      out.write("					let dtMM = dt.getMonth();\r\n");
      out.write("					let dtDD = dt.getDate();\r\n");
      out.write("					let dtHH = dt.getHours();\r\n");
      out.write("					let dtMI = dt.getMinutes();\r\n");
      out.write("					let dtResult = dtYY + \"-\" + dtMM + \"-\" + dtDD + \" \" + dtHH + \":\" + dtMI;\r\n");
      out.write("					console.log(\"insertDate : \" + dtResult);\r\n");
      out.write("					//내용이 길어서 50자로 해보자\r\n");
      out.write("					let cont = item.content + \"...\";\r\n");
      out.write("					\r\n");
      out.write("					let content = \"\";\r\n");
      out.write("					content += \"<div class='list-group-item' value='\"+item.bookId+\"'><div class='row'>\";\r\n");
      out.write("						content += \"<div class='col-auto'><img class='img-fluid' src='/resources/upload\"+filename+\"' alt='Photo' style='max-height: 160px;'></div>\";\r\n");
      out.write("						content += \"<div class='col px-4'><div>\";\r\n");
      out.write("						content += \"<div class='float-right'>\"+dtResult+\"</div>\";\r\n");
      out.write("						content += \"<h3><a href='javascript:fn_go(\"+item.bookId+\")'>\"+item.title+\"</a></h3>\";\r\n");
      out.write("						content += \"<p class='mb-0'>\"+cont.substring(0,50)+\"</p>\";\r\n");
      out.write("					content += \"</div></div></div></div>\";\r\n");
      out.write("					\r\n");
      out.write("					$(\".list-group\").append(content);	\r\n");
      out.write("					\r\n");
      out.write("				});\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("});//end function\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("// 4) 날짜 생성 함수\r\n");
      out.write("// 사용법 : fn_getInsertDate(item.insertDate)\r\n");
      out.write("function fn_getInsertDate(geta){\r\n");
      out.write("   let dt = new Date(geta);\r\n");
      out.write("   let dtYY = dt.getFullYear();\r\n");
      out.write("   let dtMM = dt.getMonth();\r\n");
      out.write("   let dtDD = dt.getDate();\r\n");
      out.write("   let dtHH = dt.getHours();\r\n");
      out.write("   let dtMI = dt.getMinutes();\r\n");
      out.write("   let dtResult = dtYY + \"-\" + dtMM + \"-\" + dtDD + \" \" + dtHH + \":\" + dtMI;\r\n");
      out.write("   console.log(\"insertDate : \" + dtResult);\r\n");
      out.write("   \r\n");
      out.write("   return dtResult;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function fn_go(geta){\r\n");
      out.write("	let str = geta;\r\n");
      out.write("	console.log(\"str : \" + str);\r\n");
      out.write("	\r\n");
      out.write("	$.each(bookVOList,function(index,item){\r\n");
      out.write("		let bookId = item.bookId;\r\n");
      out.write("		if(str==bookId){\r\n");
      out.write("// 			console.log(\"item : \" + JSON.stringify(item));\r\n");
      out.write("			//책 아이디(bookId)\r\n");
      out.write("			$(\"#bookId\").val(item.bookId);\r\n");
      out.write("			//제목(title)\r\n");
      out.write("			$(\"#title\").val(item.title);\r\n");
      out.write("			//카테고리(category)\r\n");
      out.write("			$(\"#category\").val(item.category).prop(\"selected\",true);\r\n");
      out.write("			//가격(price)\r\n");
      out.write("			$(\"#price\").val(item.price);\r\n");
      out.write("			//입력 일자(insertDate)\r\n");
      out.write("			$(\"#insertDate\").val(fn_getInsertDate(item.insertDate));			\r\n");
      out.write("			//책 내용\r\n");
      out.write("			CKEDITOR.instances.content.setData(item.content);\r\n");
      out.write("			//입력이 완료된 후 모달창 닫기\r\n");
      out.write("			$(\"#modal-lg\").modal(\"hide\"); //show : 모달창 보임\r\n");
      out.write("			\r\n");
      out.write("			//파일 요소의 disabled를 삭제\r\n");
      out.write("			$(\"#input_imgs\").removeAttr(\"disabled\");\r\n");
      out.write("			\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
